import * as fs from "fs";
import * as path from "path";

interface ForgeParams {
  description: string;
  outputDir?: string;
  framework?: "crewai" | "langgraph" | "autogen" | "basic";
}

/**
 * Generate agent.py content based on framework and description.
 */
function generateAgentPy(description: string, framework: string): string {
  const frameworkImports: Record<string, string> = {
    basic: "",
    crewai: "from crewai import Agent, Task, Crew\n",
    langgraph: "from langgraph.graph import StateGraph, END\nfrom typing import TypedDict, Annotated\nimport operator\n",
    autogen: "import autogen\n",
  };

  const frameworkStub: Record<string, string> = {
    basic: `    # TODO: implement your agent logic here
    # Tip: use httpx for HTTP calls, openai for LLM calls
    result = f"Processed: {input_data}"
    return result`,

    crewai: `    # TODO: define your CrewAI agents and tasks
    researcher = Agent(
        role="Researcher",
        goal="Research and gather information",
        backstory="Expert researcher with broad knowledge",
        verbose=False
    )
    
    task = Task(
        description=f"Process this request: {input_data}",
        agent=researcher,
        expected_output="A detailed response"
    )
    
    crew = Crew(agents=[researcher], tasks=[task], verbose=False)
    result = crew.kickoff()
    return str(result)`,

    langgraph: `    # TODO: define your LangGraph state and nodes
    class State(TypedDict):
        input: dict
        output: Annotated[str, operator.add]
    
    def process_node(state: State) -> State:
        # Your node logic here
        return {"output": f"Processed: {state['input']}"}
    
    graph = StateGraph(State)
    graph.add_node("process", process_node)
    graph.set_entry_point("process")
    graph.add_edge("process", END)
    
    app = graph.compile()
    final_state = app.invoke({"input": input_data, "output": ""})
    return final_state["output"]`,

    autogen: `    # TODO: define your AutoGen agents
    llm_config = {"model": "gpt-4o", "api_key": os.getenv("OPENAI_API_KEY")}
    
    assistant = autogen.AssistantAgent(
        name="assistant",
        llm_config=llm_config,
        system_message="You are a helpful assistant."
    )
    
    user_proxy = autogen.UserProxyAgent(
        name="user_proxy",
        human_input_mode="NEVER",
        max_consecutive_auto_reply=5,
        code_execution_config=False
    )
    
    messages: list = []
    user_proxy.initiate_chat(
        assistant,
        message=f"Process: {input_data}",
        silent=True,
        callback=lambda msg: messages.append(msg)
    )
    
    last_msg = assistant.last_message(user_proxy)
    return last_msg.get("content", "No result") if last_msg else "No result"`,
  };

  const extraImports = frameworkImports[framework] || "";
  const stub = frameworkStub[framework] || frameworkStub["basic"];

  return `import os
${extraImports}from masumi.agent import MasumiAgent
from dotenv import load_dotenv

load_dotenv()

# ─────────────────────────────────────────────────────────────────────────────
# Agent: ${description}
# Framework: ${framework}
# Generated by MasumiForge 🔨
# ─────────────────────────────────────────────────────────────────────────────

# Define what input your agent expects (JSON Schema)
INPUT_SCHEMA = {
    "type": "object",
    "properties": {
        "input": {
            "type": "string",
            "description": "The main input for this agent"
        }
    },
    "required": ["input"]
}

# Provide a demo so buyers can preview your agent on Sokosumi
DEMO = {
    "input": [
        {"key": "input", "value": "example input"}
    ],
    "output": "Example output from ${description}"
}


async def process_job(job_id: str, input_data: dict) -> str:
    """
    Core agent logic. Called by the Masumi framework when a paid job starts.
    
    Args:
        job_id: Unique job identifier
        input_data: Dict matching INPUT_SCHEMA
    
    Returns:
        Result as a string (will be hashed per MIP-004 and unlock payment)
    """
${stub.split("\n").map((l: string) => `    ${l}`).join("\n")}


if __name__ == "__main__":
    agent = MasumiAgent(
        process_job=process_job,
        input_schema=INPUT_SCHEMA,
        demo=DEMO
    )
    agent.run(host="0.0.0.0", port=8000)
    # Your agent is now running at http://localhost:8000
    # Next: register at http://localhost:3001/admin to get your AGENT_IDENTIFIER
`;
}

/**
 * Generate .env.example content.
 */
function generateEnvExample(): string {
  return `# Masumi Network Configuration
# Copy this to .env and fill in your values

PAYMENT_SERVICE_URL=http://localhost:3001/api/v1
PAYMENT_API_KEY=your_api_key_here
AGENT_IDENTIFIER=  # Set after registration at http://localhost:3001/admin
SELLER_VKEY=your_seller_vkey_here
NETWORK=Preprod

# Optional: LLM API keys if your agent uses them
# OPENAI_API_KEY=sk-...
# ANTHROPIC_API_KEY=sk-ant-...
`;
}

/**
 * Generate requirements.txt based on framework.
 */
function generateRequirements(framework: string): string {
  const base = `masumi
python-dotenv
httpx
`;

  const extras: Record<string, string> = {
    basic: "",
    crewai: "crewai\n",
    langgraph: "langgraph\nlangchain\n",
    autogen: "pyautogen\n",
  };

  return base + (extras[framework] || "");
}

/**
 * Generate a README for the forged agent.
 */
function generateAgentReadme(description: string, framework: string): string {
  return `# Masumi Agent

> ${description}

Generated by [MasumiForge 🔨](https://github.com/enjojoy/masumiforge)

## Setup

\`\`\`bash
pip install -r requirements.txt
cp .env.example .env
# Fill in .env with your Payment Service details
\`\`\`

## Run

\`\`\`bash
masumi run agent.py
# or
python agent.py
\`\`\`

## Register on Masumi

1. Start the agent: \`masumi run agent.py\`
2. Open admin UI: http://localhost:3001/admin
3. Register your agent, copy the \`AGENT_IDENTIFIER\`
4. Add to \`.env\`: \`AGENT_IDENTIFIER=your_id_here\`
5. Restart — you're live on [Sokosumi](https://preprod.sokosumi.com/agents)!

## Framework: ${framework}

## Test locally

\`\`\`bash
curl -X POST http://localhost:8000/start_job \\
  -H "Content-Type: application/json" \\
  -d '{"identifier_from_purchaser": "test-001", "input_data": [{"key": "input", "value": "test"}]}'
\`\`\`
`;
}

/**
 * Main forge function — scaffolds a new Masumi agent from a description.
 */
export async function forge(params: ForgeParams, _config: any): Promise<any> {
  const description = params.description;
  const framework = params.framework || "basic";
  const outputDir = path.resolve(params.outputDir || "./agent");

  // Create output directory
  fs.mkdirSync(outputDir, { recursive: true });

  const files: string[] = [];

  // Generate agent.py
  const agentPyPath = path.join(outputDir, "agent.py");
  fs.writeFileSync(agentPyPath, generateAgentPy(description, framework));
  files.push("agent.py");

  // Generate .env.example
  const envPath = path.join(outputDir, ".env.example");
  fs.writeFileSync(envPath, generateEnvExample());
  files.push(".env.example");

  // Generate requirements.txt
  const reqPath = path.join(outputDir, "requirements.txt");
  fs.writeFileSync(reqPath, generateRequirements(framework));
  files.push("requirements.txt");

  // Generate README.md
  const readmePath = path.join(outputDir, "README.md");
  fs.writeFileSync(readmePath, generateAgentReadme(description, framework));
  files.push("README.md");

  const summary = `✅ Forged Masumi agent in \`${outputDir}\`

**Files created:**
${files.map((f) => `  • ${f}`).join("\n")}

**Description:** ${description}
**Framework:** ${framework}

---

**Next steps:**

1. \`cd ${outputDir}\`
2. \`pip install -r requirements.txt\`
3. \`cp .env.example .env\` — fill in your Payment Service details
4. Implement your logic in \`agent.py\` → \`process_job()\`
5. \`masumi run agent.py\` — starts your agent on port 8000
6. Register at **http://localhost:3001/admin** to get your \`AGENT_IDENTIFIER\`
7. Add \`AGENT_IDENTIFIER=<your_id>\` to \`.env\` and restart
8. 🎉 You're live on [Sokosumi](https://preprod.sokosumi.com/agents)!

**Test locally:**
\`\`\`bash
curl -X POST http://localhost:8000/start_job \\
  -H "Content-Type: application/json" \\
  -d '{"identifier_from_purchaser": "test-001", "input_data": [{"key": "input", "value": "test"}]}'
\`\`\``;

  return {
    content: [{ type: "text", text: summary }],
  };
}
